[build] publish = "public" command = "hugo --gc --minify -b $URL"
[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[build.environment]
HUGO_VERSION = "0.128.2" # change to your preferred Hugo version
HUGO_ENV = "production"